### ISSUE TITLE
Decoder Tests Fail

### ISSUE THREAD

**Issue by jnnks** [ralfbiedert/openh264-rs#63] opened 2024-11-14 09:52 UTC
Hi,

some of the decoder tests fail:
```
test what_goes_around_comes_around ... FAILED
test can_access_raw_api ... ok
test can_decode_single ... FAILED
test can_get_decoder ... ok
test can_decode_multi_to_end ... FAILED
test fails_on_truncated ... ok
test can_decode_multi_by_step ... FAILED
test decodes_file_requiring_flush_frame ... FAILED
```

Can you describe how to setup the tests?
All of the encode tests work fine.

<details>
<summary>Full Output</summary>

```
running 25 tests
test formats::rgb::tests::abgr_slice_2x2 ... ok
test formats::rgb::tests::argb_slice_2x2 ... ok
test error::test::errors_wont_panic ... ok
test formats::rgb::tests::bgr_slice_4x4 ... ok
test formats::rgb::tests::bgra_slice_2x2 ... ok
test formats::rgb::tests::rgb_slice_4x4 ... ok
test formats::rgb::tests::rgba_slice_2x2 ... ok
test formats::yuv::tests::rgb_to_yuv_conversion_black_2x2 ... ok
test formats::yuv::tests::rgb_to_yuv_conversion_red_2x4 ... ok
test formats::yuv::tests::rgb_to_yuv_conversion_white_4x2 ... ok
test formats::yuv::tests::test_new_stride_less_than_width - should panic ... ok
test formats::yuv::tests::test_new_u_length_not_matching - should panic ... ok
test formats::yuv::tests::test_new_u_stride_less_than_half_width - should panic ... ok
test formats::yuv::tests::test_new_v_length_not_matching - should panic ... ok
test formats::yuv::tests::test_new_v_stride_less_than_half_width - should panic ... ok
test formats::yuv::tests::test_new_valid ... ok
test formats::yuv::tests::test_new_y_length_not_matching - should panic ... ok
test time::test::timestamps_work ... ok
test utils::test::nal_mark_empty ... ok
test utils::test::nal_mark_multiple_marks ... ok
test utils::test::nal_mark_multiple_marks_same_vec ... ok
test utils::test::nal_mark_no_mark ... ok
test utils::test::nal_mark_single_mark ... ok
test utils::test::nal_mark_stream_boundary ... ok
test utils::test::splits_at_nal ... ok

test result: ok. 25 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/decode.rs (/home/jannik/workspace/openh264-rs/target/debug/deps/decode-1331be40fec42b26)

running 8 tests
test what_goes_around_comes_around ... FAILED
test can_get_decoder ... ok
test can_decode_multi_by_step ... FAILED
test fails_on_truncated ... ok
test can_decode_multi_to_end ... FAILED
test can_access_raw_api ... ok
test decodes_file_requiring_flush_frame ... FAILED
test can_decode_single ... FAILED

failures:

---- what_goes_around_comes_around stdout ----
thread 'what_goes_around_comes_around' panicked at openh264/src/formats/rgb.rs:178:1:
assertion `left == right` failed
  left: 130
 right: 49152
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- can_decode_multi_by_step stdout ----
thread 'can_decode_multi_by_step' panicked at openh264/tests/decode.rs:85:5:
assertion failed: last_was_ok

---- can_decode_multi_to_end stdout ----
Error: Error { native: 4, decoding_state: 0, misc: None }

---- decodes_file_requiring_flush_frame stdout ----
thread 'decodes_file_requiring_flush_frame' panicked at openh264/tests/decode.rs:146:33:
No decoded data

---- can_decode_single stdout ----
Error: Error { native: 4, decoding_state: 0, misc: None }


failures:
    can_decode_multi_by_step
    can_decode_multi_to_end
    can_decode_single
    decodes_file_requiring_flush_frame
    what_goes_around_comes_around

test result: FAILED. 3 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--test decode`
```
</details>

**Comment by ralfbiedert** [comment] 2024-11-16 18:55
I can't reproduce that. Could you post the output of  `rustc -vV` ?

**Comment by jnnks** [comment] 2024-11-20 08:11
`rustc -vV`:
```
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: x86_64-unknown-linux-gnu
release: 1.80.1
LLVM version: 18.1.7
```

____
`git rev-parse HEAD`: `c6a5ecbe6d7762aba87e6091ef6307572c10610d`
____

`git status --short`:  ` ` (empty)

____

The benchmarks do not compile either, due to `#![feature(test)]` not being available on the stable release channel.

Let me know if I can help.
I wanted to look at the "Faster YUV to RGB conversion" from the README.md/Contributing afterwards.

**Comment by ralfbiedert** [comment] 2024-11-20 08:34
Is it possible that you didn't use Git LFS to check out the test files? For example, can you verify your `openh264/tests/data` folder looks like so (check the file sizes):

![image](https://github.com/user-attachments/assets/7af39a3d-ea68-420b-93ec-8cd79693571c)

**Comment by jnnks** [comment] 2024-11-21 11:03
Ah, great. Cloning the repo with git-lfs installed has fixed the issue. The tests run successfully now.

Why did you decide to use LFS? Seems like multi_1024x768.bmp is the largest file and that should not change too often.

**Comment by ralfbiedert** [comment] 2024-11-21 12:29
I find it good practice to register all (known) binary file types with LFS right at the start of a project. 

They might actually change over the life of a project, sometimes even within a few commits, and I don't want people to check out old files that are orders of magnitude larger than the entire rest of the project. 

I'm closing this issue for now, please comment / reopen if some other test issue came up.

**Closed by ralfbiedert** 2024-11-21 12:29 UTC
Labels: bug, needs-discussion
